server {
    listen 80;
    root /usr/share/nginx/site;
    index index.html;

    location ~* \.(js|css|webp|svg|png|ico|woff2|woff|ttf|map)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri /index.html;
    }
}
